[terminal]
# The VT to run the greeter on. Can be "next", "current" or a number
# designating the VT.
vt = 1

# The default session, also known as the greeter.
[default_session]

# `agreety` is the bundled agetty/login-lookalike. You can replace `/bin/sh`
# with whatever you want started, such as `sway`.
# command = "tuigreet --remember --time --asterisks --theme 'border=magenta;text=cyan;prompt=green;time=red;action=blue;button=yellow;container=darkgray;input=red' --greeting 'Welcome to Linux' --cmd start-hyprland -- -c /home/fossil/.config/hypr/hyprland.lua"
# command = "tuigreet --config /etc/tuigreet/config.toml --cmd start-hyprland -- -c /home/fossil/.config/hypr/hyprland.lua"
command = "tuigreet --remember --remember-user-session --asterisks --time --time-format '%-I:%M %p' --greeting 'Welcome to Nocturne' --theme 'border=blue;text=white;time=blue;container=black;title=cyan;greet=white;prompt=blue;input=white;action=gray;button=bright-blue' --cmd start-hyprland -- -c /home/fossil/.config/hypr/hyprland.lua"

# The user to run the command as. The privileges this user must have depends
# on the greeter. A graphical greeter may for example require the user to be
# in the `video` group.
user = "greeter"
