# preload = /home/fossil/Pictures/wall/gargantua-black-3840x2160-9621.jpg
# wallpaper = , /home/fossil/Pictures/wall/gargantua-black-3840x2160-9621.jpg
# splash = false

wallpaper {
	monitor = 
	path = /home/fossil/Pictures/wall/gargantua-black-3840x2160-9621.jpg
}
