style = "auto"
store_failed = false
show_numeric_shortcuts = false
inline_height = 0
show_preview = true
enter_accept = true
search_mode = "daemon-fuzzy"

command_chaining = true


[stats]
common_subcommands = [
  "apt",
  "cargo",
  "composer",
  "dnf",
  "docker",
  "git",
  "go",
  "ip",
  "jj",
  "kubectl",
  "nix",
  "nmcli",
  "npm",
  "pecl",
  "pnpm",
  "podman",
  "port",
  "systemctl",
  "tmux",
  "yarn",
]


[sync]
records = true

[daemon]
enabled = true
autostart = true

[search]
filters = ["global", "host", "session", "directory"]

[theme]
name = "mocha"
debug = false

[ui]
columns = [
# "duration",
"time",
"command",
]

[ai]
enabled = false
