-- ~/.config/nvim/lua/plugins/which-key.lua
return {
	{
		"folke/which-key.nvim",
		event = "VeryLazy",
		opts = {
			preset = "modern",
			delay = 300,
			win = { border = "rounded", padding = { 1, 2 }, no_overlap = true, title = true, title_pos = "center" },
			layout = { width = { min = 24, max = 60 }, spacing = 3 },
			sort = { "manual", "group", "alphanum", "mod" },
			icons = {
				mappings = true,
				breadcrumb = "»",
				separator = "➜",
				group = "+",
				ellipsis = "…",
				rules = {},
				colors = true,
			},
			triggers = { { "<auto>", mode = "nixsotc" }, { "s", mode = "n" } },
			plugins = {
				marks = true,
				registers = true,
				spelling = { enabled = true, suggestions = 20 },
				presets = {
					operators = false,
					motions = false,
					text_objects = false,
					windows = false,
					nav = false,
					z = false,
					g = false,
				},
			},
			show_help = true,
			show_keys = true,
			disable = { buftypes = {}, filetypes = { "telescopeprompt", "lazy", "mason" } },
			spec = {
				{ "<leader>b", group = "Buffers" },
				{ "<leader>c", group = "Code" },
				{ "<leader>f", group = "Find / Format" },
				{ "<leader>g", group = "Git" },
				{ "<leader>m", group = "Multicursor" },
				{ "<leader>s", group = "Windows" },
				{ "s", group = "Surround", mode = "n" },
				{ "<leader>u", desc = "Undo History" },
				{ "<leader>w", desc = "Save File" },
				{ "<leader>q", desc = "Quit" },
				{ "<leader>y", desc = "Yank To Clipboard", mode = { "n", "v" } },
				{ "<leader>a", desc = "Align", mode = "x" },
				{ "<leader>fd", desc = "Format Buffer" },
				{ "<leader>rn", desc = "Rename Symbol" },
				{ "<leader>ca", desc = "Code Action" },
				{ "<C-h>", desc = "Focus Left Window" },
				{ "<C-j>", desc = "Focus Lower Window" },
				{ "<C-k>", desc = "Focus Upper Window" },
				{ "<C-l>", desc = "Focus Right Window" },
				{ "K", desc = "Hover Documentation" },
				{ "gd", desc = "Go To Definition" },
				{ "gr", desc = "Go To References" },
			},
		},
	},
}
