include theme.conf
include appearance.conf
include keybindings.conf
include shell.conf
include tabs.conf
include colors.conf
include kittens.conf

# Fonts
font_family      Maple Mono NF
bold_font        auto
italic_font      auto
bold_italic_font auto

font_size 15.0

adjust_line_height 0
adjust_column_width 0

disable_ligatures never

# Cursor
# can be block, beam or underline
cursor_shape beam
cursor_beam_thickness 1.0
cursor_underline_thickness 2

cursor_blink_interval 0
cursor_stop_blinking_after 0

# Must be 0 to disable
cursor_trail 1
# later value must be greater than or equal
cursor_trail_decay 0.1 0.3

shell_integration no-cursor

# Scroll
scrollbar never
scrollback_lines 20000

scrollback_fill_enlarged_window yes

# Mouse
mouse_hide_wait 1.5
# the interval between successive clicks to detect double/triple clicks in seconds.
# Negative numbers will use the system default instead, if available
# or fallback to 0.5
click_interval -1.0

# URL handling
# can be none, straight, double, curly, dotted & dashed
url_style curly

# Clipboard
copy_on_select clipboard
strip_trailing_spaces smart
paste_actions quote-urls-at-prompt,confirm,confirm-if-large

# Performance
repaint_delay 10
sync_to_monitor no
input_delay 3

# Terminal Bell
enable_audio_bell no
visual_bell_duration 0
wayland_titlebar_color system




# Open a new split window (side/bottom) in the same directory
map ctrl+shift+alt+enter new_window_with_cwd

# Open a new tab in the same directory
map ctrl+shift+alt+t new_tab_with_cwd
